
export const ACCOUNT_TYPE = {
  SYSTEM: "SYSTEM",
  GOOGLE: "GOOGLE",
  GITHUB: "GITHUB",
};

export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
